config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'corporate/send_log_mail', to: 'corporate#send_log_mail'
  get 'corporate/login'
  get 'corporate/new_team_member'
  post 'corporate/save_team_member'
  post 'corporate/other_Question'
  post 'corporate/Contact'
  post 'corporate/change_password'
  post 'corporate/corporate_forgot_password'
  get 'corporate/logout'
  get '/assessor_questionnaire' => 'corporate#assessor_questionnaire'
  get 'corporate/reset_password/:token' => 'corporate#reset_password'
  post 'corporate/set_password'
  post 'corporate/impact_qustion'
  post 'users/impact_qustion'
  get 'corporate/thank_you_page'
  get 'corporate/my_account'
  get 'corporate/edit_account'
  post 'corporate/update_account'
  post 'corporate/match_password'
  post 'corporate/login_status'
  get 'corporate/summary_report/:roleid' => 'corporate#summary_report'
  get 'corporate/salary_report/:roleid' => 'corporate#salary_report'
  get 'corporate/edit_role/:roleid' => 'corporate#edit_role'
  post 'corporate/update_role'
  get 'corporate/add_role_info'
  get 'corporate/add_role_candidate_info/:roleid' => 'corporate#add_role_candidate_info'
  get 'corporate/role_summary'
  get 'corporate/dashboard'
  post 'corporate/delete_applicant'
  post 'corporate/update_application'
  get 'corporate/edit_application/:app_id' => 'corporate#edit_application'
  get 'corporate/add_role_summary/:roleid' => 'corporate#add_role_summary'
  get 'corporate/registration'
  get 'corporate/registration-recruitment'=>'corporate#registration_recruitment'
  get 'corporate/member_registration'
  get 'corporate/add_role_cl/:roleid' => 'corporate#add_role_cl'
  post 'corporate/getAllQuestion'
  get 'corporate/invite_new_member'
  post 'corporate/invite_member'
  get 'corporate/corporate_dashboard'
  get 'corporate/application/:roleid' => 'corporate#application'
  get 'corporate/job_application/:roleid' => 'corporate#job_application'
  post 'corporate/upload'
  post 'corporate/deleterole'
  post 'corporate/sort_applicants'
  post 'corporate/filter_applicants'
  post 'corporate/sort_applicants_advance'
  get 'corporate/candidate/:app_id' => 'corporate#candidate'
  post 'corporate/candidate/:app_id' => 'corporate#candidate'
  post 'corporate/select_role'
  post 'corporate/delete_member'
  post 'corporate/add_question'
  post 'corporate/delete_question'
  post 'corporate/edit_question'
  post 'corporate/send_report'
  get 'corporate/download_pdf/:resume_id' => 'corporate#download_pdf'
  get 'corporate/redirect/:token' => 'corporate#redirect'
  post 'corporate/set_user_data'
  post 'corporate/download_data'
  post 'corporate/get_seo'
  post 'corporate/get_jobs'

  post 'find_company/index'
  post 'find_company/getAllCharts'
  post 'corporate/new_member_registration'
  post 'report/CalculateIntialValues'
  post 'report/calculateUserPosition'
  post 'report/calculateIntalBar'
  post 'report/compensationGraph'
  post 'report/getCompensationChart'
  post 'report/getPromotionChart'
  post 'report/GrowthReport'
  post 'report/CLReport'
  post 'report/getInitialChart'
  post 'corporate/add_newroll_3'
  post 'users/reset_password'
  post 'users/user_reset_password'
  post 'corporate/corporate_login'
  get 'corporate/add_new_role'
  post 'corporate/add_newrole'
  post 'corporate/add_role_summary'
  post 'corporate/sign_up'
  post 'corporate/changefilter'
  post 'corporate/record_log'
  get 'corporate/get_seo'
  post 'corporate/find_company'

  get 'recruiter/registration'
  post 'recruiter/sign_up'
  get 'recruiter/reset_password/:token' => 'recruiter#reset_password'
  post 'recruiter/set_password'

  get 'admin/getDistnicValues'
  get 'qustioner/getStarted'
  get 'qustioner/gotoQuiz'
  post 'qustioner/getAllQuestions'
  post 'qustioner/getQuestionFactorWise'
  post 'qustioner/report'
  post 'qustioner/getGrowthChart'
  post 'qustioner/getPromationChart'
  post 'qustioner/getRoleChart'
  post 'qustioner/getScore'
  post 'qustioner/getMyLevel'
  post 'corporate/add_new_role_1'
  post 'corporate/add_newrole_3'
  get 'users/readFile'
  get 'users/SignUpForm'
  post 'users/delete_account'
  post 'users/getUserInfo'
  post 'users/show_selected_opt_details'
  post 'users/conpentency_cl_cal'
  post 'users/get_compentency_result'
  post 'users/getquestioninformation'
  post 'users/user_forgot_password'
  post 'users/getUserLevel'
  post 'users/updateUserInfo'
  post 'users/sign_up_user'
  post 'users/sign_up_initial'
  post 'users/Login_user'
  post 'users/checkUser'
  post 'users/updateUserPassword'
  post 'qustioner/getIndustryWiseAvgSalary'
  post 'qustioner/getRoleWiseAvgScore'
  post 'qustioner/getAllIndustries'
  get 'qustioner/getAllRoles'
  root 'admin#index'
  get '*any' => "corporate#error_page"

end

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "development"  %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128188545-1"></script>
  <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
          dataLayer.push(arguments);
      }

      gtag('js', new Date());

      gtag('config', 'UA-128188545-1');
  </script>
  <script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/3d22debb8efb1b74b116411ce/5bf16315961bf2b6ea0d1bcad.js");</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="{{app.description}}">
  <%= render :partial => 'layouts/google_analytics' %>
  <meta name="keywords" content="app, responsive, angular, bootstrap, dashboard, admin">
  <title data-ng-bind="pageTitle()">Leap Curve</title>
  <link rel="shortcut icon" type="image/gif/png" href="assets/favcon-titlt.png">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'appilcation' %>
  <%= csrf_meta_tags %>
  <script src="./assets/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.5.0/ui-bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.5.0/ui-bootstrap-tpls.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.2/angular-animate.min.js"></script>
  <% if $live %>
    <script src="https://code.highcharts.com/highcharts.js"></script>
  <% else %>
    <script src="http://code.highcharts.com/highcharts.js"></script>
  <% end %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
  <script src="components/highstock/highstock.js"></script>
  <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
  <script>
      function get_seo(){
          $.ajax({
              url: '/corporate/get_seo',
              data: {'path': location.hash.split('/')[2]},
              type: 'get',
              success: function (responce) {
                  if(responce!="{}"){
                      var data = responce.replace(/=>/g, ':')
                      var data1 = JSON.parse(data)
                      document.getElementsByName('description')[0].setAttribute('content', data1['description'])
                      document.getElementsByName('keywords')[0].setAttribute('content', data1['keyword'])
                      document.getElementsByTagName('title')[0].innerHTML = data1['title']
                  }else{
                      document.getElementsByTagName('title')[0].innerHTML = "Leap Curve"
                  }
              }


          });
      }
      get_seo()
  </script>
</head>
<body ng-app="naut" ng-clok="" ng-class="{ 'layout-fixed' : app.layout.isFixed, 'layout-boxed' : app.layout.isBoxed, 'layout-dock' : app.layout.isDocked, 'layout-material': app.layout.isMaterial, 'aside-offscreen' : app.sidebar.isOffscreen, 'aside-mini' : app.sidebar.isMini, 'footer-hidden': app.footer.hidden, 'in-app': !$state.includes('page')}">
<style>

  .layout_loader-overlay {
    display: block !important;
    width: 100%;
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
    background: rgba(0, 0, 0, 0.5);
    z-index: 1031;

  }
  .tooltipText {
    float: left;
    visibility: hidden;
    /* width: 120px; */
    background-color: black;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 5px;
    position: absolute;
    z-index: 1;
    right: 0;
  }
  .toltip:hover .tooltipText {
    visibility: visible !important;
  }
  .layout_loader {
    display: block !important;
    position: fixed;
    z-index: 1032;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
    border: 16px solid #f3f3f3;
    border-radius: 50%;
    border-top: 16px solid gray;
    border-bottom: 16px solid gray;
    width: 120px;
    height: 120px;
    -webkit-animation: spin 2s linear infinite;
    animation: spin 2s linear infinite;
  }

  .hide {
    display: none;
  }

  @media (max-width: 991px) {
    .layout_loader {
      position: fixed;
      z-index: 1032;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      margin: auto;
      border: 6px solid #f3f3f3;
      border-radius: 50%;
      border-top: 6px solid gray;
      border-bottom: 6px solid gray;
      width: 60px;
      height: 60px;
      -webkit-animation: spin 2s linear infinite;
      animation: spin 2s linear infinite;
    }
  }

  @-webkit-keyframes spin {
    0% {
      -webkit-transform: rotate(0deg);
    }
    100% {
      -webkit-transform: rotate(360deg);
    }
  }

  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }

</style>
<div data-ui-view="" data-autoscroll="false" ng-controller="CoreController" class="app-container" style="overflow-y: auto; height: 100vh"></div>
<div class="loader" ng-show="app.showLoader"></div>
<div class="loader-overlay" ng-show="app.showLoader"></div>
<div id="loader" class="hide">
  <div class="layout_loader"></div>
  <div class="layout_loader-overlay"></div>
</div>
<!-- Settings-->
<!--<div ng-include="'/assets/templates/settings.html'" ng-class="{'visible': showSettings}" ng-init="showSettings = false" class="settings-wrapper"></div>-->
<!-- End Settings-->
<%#= yield %>
<%= render :partial => 'corporate/normal_confirm' %>
<script>
    async function register() {
        var istrue=await normal_confirm('Are you a recruitment company?');
        if(istrue){
            location.href= '/recruiter/registration/'
        }else {
            location.href= '/corporate/registration/'
        }

    }
    async function forgot_password() {
        var istrue=await normal_confirm('Are you a recruitment company?');
        return istrue

    }
</script>
<script>
    var loader = document.getElementById('loader').classList;

    function showloader() {
        loader.add('show');
        loader.remove('hide');
    }

    function hideloader() {
        loader.remove('show');
        loader.add('hide');
    }
</script>
</body>
</html>

app/views/layouts/recruiter.html.erb
<!DOCTYPE html>
<html>
<head>
  <% get_seo_data() %>
  <title><%= @title %></title>
  <meta name="description" content="<%= @description %>">
  <%= render :partial => 'layouts/google_analytics' %>
  <meta name="keywords" content="<%= @keyword %>">
  <link rel="shortcut icon" type="image/gif/png" href="/assets/favcon-titlt.png">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <style>
    .btn-head {
      float: right;
      margin: 10px 10px 10px 0px;
      padding-right: 10px

    }

    .btn-head a {
      color: #3e3e3e;
      font-family: Montserrat-Regular;
      text-decoration: underline;
    }

    .brd {
      border-right: 1px solid black;
    }

    .tooltip:hover .tooltipText {
      visibility: visible !important;
    }

    .tooltipText {
      float: left;
      visibility: hidden;
      /*width: 120px;*/
      background-color: black;
      color: #fff;
      text-align: center;
      border-radius: 6px;
      padding: 5px 5px;

      /* Position the tooltip */
      position: absolute;
      z-index: 1;
      right: 0;
    }

    .show {
      visibility: visible !important;
    }

    #flash {
      /*float: right;*/
      /* float: right; */
      visibility: hidden;
      top: 50px !important;
      text-align: center;
      width: 25%;
      position: absolute;
      left: 37%;
      margin: auto;
      z-index: 777;
      font-weight: bold;
      font-family: Poppins-SemiBold;

    }

    @font-face {
      font-family: Montserrat-Regular;
      src: url("/assets/fonts/Montserrat-Regular.otf")
    }

    @font-face {
      font-family: Montserrat-Medium;
      src: url('/assets/fonts/Montserrat-Medium.otf')
    }

    @font-face {
      font-family: Montserrat-SemiBold;
      src: url('/assets/fonts/Montserrat-SemiBold.otf')
    }

    @font-face {
      font-family: Montserrat-Bold;
      src: url('/assets/fonts/Montserrat-Bold.otf')
    }

    @font-face {
      font-family: Poppins-Regular;
      src: url('/assets/fonts/Poppins-Regular.ttf')
    }

    @font-face {
      font-family: Poppins-Medium;
      src: url('/assets/fonts/Poppins-Medium.ttf')
    }

    @font-face {
      font-family: Poppins-SemiBold;
      src: url('/assets/fonts/Poppins-SemiBold.ttf')
    }

    @font-face {
      font-family: Poppins-Bold;
      src: url('/assets/fonts/Poppins-Bold.ttf')
    }

    .alert-success {
      /*visibility: visible !important;*/
      padding: 10px;
      border-radius: 2px;
      border: 1px solid gray;
      color: white;
      background-color: green;
    }

    .alert-notice {
      visibility: hidden;
      padding: 10px;
      border-radius: 2px;
      border: 1px solid gray;
      color: white;
      background-color: green;

    }

    .alert-alert {
      display: none;
    }

    .alert-warning {
      padding: 10px;
      border-radius: 3px;
      border: 1px solid gray;
      color: white;
      background-color: red;
    }

    .logo {
      float: left;
      height: 50px;
      font-size: 18px;
      padding: 15px 30px;
    }

    @media only screen and (max-width: 768px) {
      .logo {
        width: 23%;
        min-height: 50px;
      }

      #flash {
        /* float: right; */
        visibility: hidden;
        margin-top: 10px;
        text-align: center;
        width: 35%;
        position: absolute;
        left: 32%;
        margin: auto;
        z-index: 777;
        font-weight: bold;
        font-family: Arial;
      }
    }

    @media only screen and (max-width: 525px) {
      .logo {
        padding: 2% 2%;
        height: 35px;
        width: 40%;
        min-height: 0;
      }

      .btn-head {
        float: right;
        margin: 23px 4px 0px 0px;
        padding-right: 5px;
        font-size: 12px;
      }

      #flash {
        visibility: hidden;
        margin-top: 10px;
        text-align: center;
        width: 50%;
        position: absolute;
        margin: auto;
        font-size: 13px;
        left: 90px;
        z-index: 777;
        font-weight: bold;
        font-family: Arial;
      }

      .alert-success {
        padding: 2px;
        border-radius: 2px;
        border: 1px solid gray;
        color: white;
        position: absolute;
        background-color: green;
        font-size: 12px;
      }
    }
  </style>
  <style>

    .loader-overlay {
      width: 100%;
      position: fixed;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      margin: auto;
      background: rgba(0, 0, 0, 0.5);
      z-index: 1031;

    }

    .loader {
      position: fixed;
      z-index: 1032;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      margin: auto;
      border: 16px solid #f3f3f3;
      border-radius: 50%;
      border-top: 16px solid gray;
      border-bottom: 16px solid gray;
      width: 120px;
      height: 120px;
      -webkit-animation: spin 2s linear infinite;
      animation: spin 2s linear infinite;
    }

    .hide {
      display: none;
    }

    @media (max-width: 991px) {
      .loader {
        position: fixed;
        z-index: 1032;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        margin: auto;
        border: 6px solid #f3f3f3;
        border-radius: 50%;
        border-top: 6px solid gray;
        border-bottom: 6px solid gray;
        width: 60px;
        height: 60px;
        -webkit-animation: spin 2s linear infinite;
        animation: spin 2s linear infinite;
      }
    }

    @-webkit-keyframes spin {
      0% {
        -webkit-transform: rotate(0deg);
      }
      100% {
        -webkit-transform: rotate(360deg);
      }
    }

    @keyframes spin {
      0% {
        transform: rotate(0deg);
      }
      100% {
        transform: rotate(360deg);
      }
    }
    a{
      cursor: pointer;
    }
  </style>
</head>
<body style=" margin: 0;">
<header>
  <% if session.has_key?('User') && session[:User]['islogin'] %>
    <% @path = '/corporate/dashboard' %>
  <% else %>
    <% @path = '/#!/page/index#home3' %>
  <% end %>
  <a onclick="return logout(3)"><img src="/assets/logo1.png" alt="Mylestone" class="logo"></a><!--  <img src="assets/logo1.png" class="navbar-brand img-brand" class="img-responsive">-->
  <div class="btn-head">
    <% if session.has_key?('User') && session[:User]['islogin'] %>
      <%#= session[:User]['Name'] %>
      <div class="tooltip">
        <%#= link_to "LOGOUT", '', :onclick=>"logout()" %>
        <a name="LOGOUT" onclick="logout(1)" style="text-decoration: underline; cursor: pointer" class="addrole">LOGOUT</a>
        <div class="tooltipText">
          <%= session[:User]['Email'] %>
        </div>
      </div>
    <% else %>
      <!--      <div class="tooltip">-->
      <%#= link_to "LOG IN", corporate_login_path %>
      <!--      </div>-->

    <% end %>
  </div>
  <div class="btn-head brd">
    <% if session.has_key?('User') && session[:User]['islogin'] %>
      <%#= session[:User]['Name'] %>
      <%#= link_to "MY ACCOUNT", '' ,:onclick=>"return logout(2);location.href='/corporate/add_new_role'"%>
      <a onclick="return logout(2)" >MY ACCOUNT</a>
    <% else %>
      <!--      <div class="tooltip">-->
      <%#= link_to "SIGN UP", corporate_registration_path %>
      <!--      </div>-->
    <% end %>
  </div>
</header>
<main>

  <div id="flash">
    <% if flash.blank? %>
      <div class="alert-notice">!</div>
    <% else %>
      <% flash.each do |key, value| %>
        <div class="alert-<%= key %>"><%= value %></div>
      <% end %>
    <% end %>
  </div>
  <div class="hide" id="loader">
    <div class="loader"></div>
    <div class="loader-overlay"></div>
  </div>

  <%= yield %>
  <% if session[:User].present? && session[:User]['que_optional'].present?
       session[:User]['que_optional'] = Hash.new
     end
  %>
</main>
<script type="text/javascript">
    async function submit_role(page) {
        var part_value=0;
        var post
        if (page == 'add_new_role') {
            post = '/corporate/add_newrole';
        } else if (page == 'edit_role') {
            post = '/corporate/update_role';
        }
        var partial_btn = $(".question.show button[name='partial']")
        for (var j = 0; j < partial_btn.length; j++) {
            if (partial_btn.length > 1 && partial_btn[j].value != '21') {
                if( parseInt(partial_btn[j].value) > parseInt(part_value)){
                    part_value = partial_btn[j].value;
                    // break;
                }
            }
            else {
                part_value = partial_btn[j].value;
            }

        }
        let promise = new Promise((resolve, reject) => {
            $.ajax({
                url: post,
                data: $('form').serialize() + '&partial=' + part_value+ '&logout=' + 'true',
                type: 'post',
                success: function (respose) {
                    resolve(true);
                }
            })
        });
        var result = await promise; // wait till the promise resolves (*)
        return result;

    }

    async function logout(id) {
        var issave;
        var loc = window.location.pathname.split('/');
        if (loc[2] == 'add_new_role' || loc[2] == 'edit_role') {
            // var btn = confirm('Would you like to save this role before logging out?')
            if(id==1){
                var btn = await advance_confirm('Would you like to save this role before logging out?')
                if (btn == 0) {
                    var btn1 = await submit_role(loc[2]);
                    logt()
                } else if (btn == 1) {
                    logt()
                } else {
                    // logt()
                }
            }else{
                var btn = await advance_confirm('Would you like to save this role?')
                if (btn == 0) {
                    var btn1 = await submit_role(loc[2]);

                    if (id == 3) {
                        location.href = '/corporate/dashboard'
                    }else if(id==2){
                        location.href = '/corporate/my_account'
                    }
                    return true;
                } else if (btn == 1) {
                    if (id == 3) {
                        location.href = '/corporate/dashboard'
                    } else if (id == 2) {
                        location.href = '/corporate/my_account'
                    }
                    return true;
                }else if (btn == 2) {
                    return false;
                }
            }

        }
        else {
            if(id==1) {
                logt()
            }else{
                if (id == 3) {
                    location.href = '/corporate/dashboard'
                }else if(id==2){
                    location.href = '/corporate/my_account'
                }
                return true;
            }
        }

    }

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }

    function logt() {
        showloader();
        $.ajax({
            url: '/corporate/logout',
            data: JSON.stringify({}),
            type: 'get',
            success: function (response) {
                location.href = '/#!/page/index#home3'
            }
        })

    }

    function record_log(info) {
        $.ajax({
            url: '/corporate/record_log',
            data: $('form').serialize() + '&data=' + info,
            type: 'post',
            success: function () {

            }

        })
    }

    function message(msg) {
        var alert = document.getElementById('flash');
        alert.innerHTML = msg
        alert.classList.add('alert-success')
        alert.classList.add('show')
        alert.classList.remove('hide')

        setTimeout(function () {
            alert.classList.add('hide')
            alert.classList.remove('show')
        }, 5000);

    }

    var loader = document.getElementById('loader').classList;

    function showloader() {
        loader.add('show');
        loader.remove('hide');
    }

    function hideloader() {
        loader.remove('show');
        loader.add('hide');
    }

    setTimeout(function () {
        document.getElementById('flash').classList.remove('show');
    }, 5000)
    var old_url = window.location.pathname;
    // setInterval(function () {
    //     if (window.location.pathname != '/corporate/login'&&window.location.pathname != '/corporate/registration') {
    //         $.ajax({
    //             url: "/corporate/login_status",
    //             type: 'post',
    //             data: $('form').serialize(),
    //             success: function (response) {
    //                 if (response == 'false') {
    //                     location.reload();
    //                 }
    //
    //             }
    //
    //         })
    //     }
    //     else if (window.location.pathname == '/corporate/login'&&window.location.pathname != '/corporate/registration') {
    //         $.ajax({
    //             url: "/corporate/login_status",
    //             type: 'post',
    //             data: $('form').serialize(),
    //             success: function (response) {
    //                 if (response == 'true') {
    //                     window.location.pathname = '/corporate/dashboard'
    //                 }
    //
    //             }
    //
    //         })
    //     }
    // }, 3000)
</script>
</body>
</html>